/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	Packages:      [
		{
			type:    "autogenerated",
			dirName: "packages",
		},
		{
			type:  "link",
			label: "Documentation",
			href:  "/advanced",
		},
		{
			type:  "link",
			label: "Plugins",
			href:  "/plugins",
		},
		{
			type:  "link",
			label: "Docker",
			href:  "/docker",
		},
	],
	Docker:        [
		{
			type:    "autogenerated",
			dirName: "docker",
		},
		{
			type:  "link",
			label: "Documentation",
			href:  "/advanced",
		},
		{
			type:  "link",
			label: "Packages",
			href:  "/packages",
		},
		{
			type:  "link",
			label: "Plugins",
			href:  "/plugins",
		},
	],
	Plugins:       [
		{
			type:    "autogenerated",
			dirName: "plugins",
		},
		{
			type:  "link",
			label: "Documentation",
			href:  "/advanced",
		},
		{
			type:  "link",
			label: "Packages",
			href:  "/packages",
		},
		{
			type:  "link",
			label: "Docker",
			href:  "/docker",
		},
	],
	Documentation: [
		{
			type: "doc",
			id:   "intro",
		},
		{
			type:  "category",
			label: "Getting Started",
			link:  {
				type: "generated-index",
			},
			items: [
				{
					type:    "autogenerated",
					dirName: "getting-started",
				},
			],
		},
		{
			type:  "category",
			label: "Advanced",
			link:  {
				type: "generated-index",
			},
			items: [
				{
					type:    "autogenerated",
					dirName: "advanced",
				},
			],
		},
		{
			type:  "link",
			label: "Packages",
			href:  "/packages",
		},
		{
			type:  "link",
			label: "Plugins",
			href:  "/plugins",
		},
		{
			type:  "link",
			label: "Docker",
			href:  "/docker",
		},
	],


	// But you can create a sidebar manually
	/*
	 tutorialSidebar: [
	 'intro',
	 'hello',
	 {
	 type: 'category',
	 label: 'Tutorial',
	 items: ['tutorial-basics/create-a-document'],
	 },
	 ],
	 */
};

module.exports = sidebars;
